### ISSUE TITLE
solr script executable permissions

### ISSUE THREAD

**Issue by miguel-negrao** [labcif/autopsy-packager#10]
The file `/opt/autopsy/autopsy/solr/bin/autopsy-solr` , which is a shell script, must have executable permissions in order for autopsy to be able to start the solr server. It must have executable permissions for "others", since the file is owned by root. @ljmf00 can you adapt the build script to solve this ?

The debian dependencies are also not correct, but I will make a pull-request for that.

The script mentioned above starts Solr in a way that it tries to write log files into a directory in /opt/autopsy/autopsy/solr/ which it can't because it doesn't have root permissions. Currently a workaround is to do something like `export SOLR_LOGS_DIR=$HOME`, but it would be nice to solve this in the package itself. Ideally the solr server should write the logs somewhere that it has permissions like `~/.autopsy/solr_logs`. Probably this would require editing the script.

With these changes done by hand I was able to install from the 4.19.2 .deb and run well with solr working.

**Comment by ljmf00** [comment]
> The debian dependencies are also not correct, but I will make a pull-request for that.

Btw, can you file a bug report/issue for this?

**Comment by miguel-negrao** [comment]
I will do a pull-request with everything once I have the install script working.

**Comment by ljmf00** [comment]
Added upstream issue: https://github.com/sleuthkit/autopsy/issues/7547
